project: 
  type: book

book: 
  page-navigation: true
  title: "Pacific NCRMP Reef Fish Report" 
  author:
    - name: Kaylyn McCoy
      affiliations:
        - name: NOAA Fisheries
          department: Pacific Islands Fisheries Science Center
    - name: Andrew Shantz
      affiliations:
        - name: NOAA Fisheries
          department: Pacific Islands Fisheries Science Center
  chapters:
    - index.qmd
    - MainBodyText.qmd
    - LiteratureCited.qmd
    - Appendix.qmd
    
bibliography: references.bib
csl: apa.csl

format:
  docx:
    toc: true
    toc-depth: 4
    reference-doc: OFFICIAL_PIFSC_Data_Reports_Apr_2025.docx
    appendix-style: "letters"
    always_allow_html: false
