# Literature Cited {.unnumbered}

```{r}
#| echo: false

# Two options for incorporating your references are included here.  
# CHOOSE ONE
# Regardless of which option you choose, you'll need to edit _quarto.yml to 
# reflect your choice

# If you use Zotero, you can integrate it directly into RStudio.  This makes it
# much easier to use OPTION ONE below.
# To learn how to connect EndNote or Mendeley to Zotero, and 
# to learn how to connect Zotero to RStudio, see:
# https://nmfs-opensci.github.io/Quarto-Workshop-2024/tutorials/tutorial-6.html
# and 
# https://drive.google.com/file/d/1_uZO7zA_tnqdf7jo8tZ2poa5ALidTHEN/view

# OPTION ONE: BibTeX
# You can add BibTeX entries to references.bib.  
# If you have connected your Zotero library to RStudio, you can cite papers
# using @ (see the "Citations and references" section in the file 
# "MainBodyText.qmd" for an example of how to do this).
# Otherwise, https://www.doi2bib.org/ can generate these for you.  
# And check out https://libguides.nps.edu/citation/bibtex for help creating 
# citations for things like government reports.
# You can also use citation software like Papers to generate a BibTex file.  
# Some benefits of using BibTex references are that they enable easy in-text
# citation, your references will only appear if you actually cite them, and
# your references will be properly formatted.
# IF YOU USE THIS OPTION, delete the line of code in _quarto.yml that adds
# LiteratureCited.qmd to the document.  You can leave the LiteratureCited.qmd 
# file itself as-is.
# ALSO
# In Word, you'll need to apply the "Literature" style to your references.

# OPTION TWO: References by hand
# If you prefer to enter citations by hand, be sure you're using APA 7th edition.
# Enter them on the lines between the Div (:::)
# End each citation with two spaces
# Leave a blank line between citations so that the formatting is applied correctly.
# Note that you'll still need to italicize journal names and volumes yourself.
# You can do this by placing the text within pair of single asterisks or underscores.
# Some benefits of doing references by hand are that it may work better for obscure
# references and that you'll get a cozy feeling of nostalgia.
# IF YOU USE THIS OPTION, delete the line of code in _quaro.yml that adds 
# References.qmd to the document.  You can leave the References.qmd file itself
# as-is.
```

::: {custom-style="Literature"}
Ault, J.S., Smith, S.G., Bohnsack, J.A., Luo, J., Harper, D.E., & McClellan, D.B. (2006). Building sustainable fisheries in Florida’s coral reef ecosystem: Positive signs in the dry Tortugas. Bull. Mar. Sci. 78(3):633–654.

Ayotte, P., McCoy, K., Heenan, A., Williams, I., & Zamzow, J. (2015). Coral Reef Ecosystem Program standard operating procedures: Data collection for Rapid Ecological Assessment fish surveys. Pacific Islands Fisheries Science Center Administrative Report H-15-07, 39 p. 

Froese, R., & Pauly, D. (2010). “FishBase.” http://www.fishbase.org/search.php

Kulbicki, M., Guillemot, N., & Amand, M. (2005). A general approach to length-weight relationships for New Caledonian lagoon fishes. Cybium. 29(3):235–252.

NOAA Coral Program. (2021). National Coral Reef Monitoring Plan. NOAA Coral Reef Conservation Program. 40 p. https://repository.library.noaa.gov/view/noaa/32748

NOAA Coral Reef Conservation Program. (2009). Goals & Objectives 2010–2015, NOAA Coral Reef Conservation Program. 40 p. 
NOAA CRCP. (2014). National Coral Reef Monitoring Plan. NOAA Coral Reef Conservation Program. 40 p. ftp://ftp.library.noaa.gov/noaa_documents.lib/CoRIS/CRCP/noaa_crcp_national_coral_reef_monitoring_plan_2014.pdf.

R Development Core Team. (2011). R: A Language and Environment for Statistical Computing, Vienna, Austria.

Smith, S.G., Ault, J.S., Bohnsack, J.A., Harper, D.E., Luo, J., & McClellan, D.B. (2011). Multispecies survey design for assessing reef-fish stocks, spatially explicit management performance, and ecosystem condition. Fish Res.109(1):25–41.

Wickham, H. (2016). ggplot2: Elegant Graphics for Data Analysis. Springer-Verlag, New York.

Williams, I.D., Richards, B.L., Sandin, S.A., Baum, J.K., Schroeder, R.E., Nadon, M.O., Zgliczynski, B., Craig, P., McIlwain. J.L., & Brainard, R.E. (2011). Differences in reef fish assemblages between populated and remote reefs spanning multiple archipelagos across the central and western Pacific. J. Mar. Biol. Article ID 826234, 14 p. https://doi.org/10.1155/2011/826234 

:::